# Generated by Django 5.1.4 on 2025-03-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиофайл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аудио и текст',
                'verbose_name_plural': 'Аудио и тексты',
            },
        ),
    ]
